export const countryList = [
  {key: 1, value: "AED(아랍에미리트/디르함)"}, 
  {key: 2, value: "ATS(오스트리아/실링)"}, 
  {key: 3, value: "AUD(호주/달러)"}, 
  {key: 4, value: "BEF(벨기에/프랑)"}, 
  {key: 5, value: "BHD(바레인/디나르)"}, 
  {key: 6, value: "CAD(캐나다/달러)"}, 
  {key: 7, value: "CHF(스위스/프랑)"}, 
  {key: 8, value: "CNH(중국/위안)"}, 
  {key: 9, value: "DEM(독일/마르크)"},
  {key: 10, value: "DKK(덴마크/크로네)"},
  {key: 11, value: "ESP(스페인/페세타)"}, 
  {key: 12, value: "EUR(유럽 연합/유로)"}, 
  {key: 13, value: "FIM(핀란드/마르카)"},
  {key: 14, value: "FRF(프랑스/프랑)"},
  {key: 15, value: "GBP(영국/파운드)"}, 
  {key: 16, value: "HKD(홍콩/달러)"}, 
  {key: 17, value: "IDR(인도네시아/루피아)"},
  {key: 18, value: "ITL(이탈리아/리라)"}, 
  {key: 19, value: "JPY(일본/옌)"}, 
  {key: 20, value: "KRW(한국/원)"}, 
  {key: 21, value: "KWD(쿠웨이트/디나르)"},
  {key: 22, value: "MVR(말레이지아/링기트)"}, 
  {key: 23, value: "NLG(네델란드/길더)"}, 
  {key: 24, value: "NOK(노르웨이/크로네)"}, 
  {key: 25, value: "NZD(뉴질랜드/달러)"}, 
  {key: 26, value: "SAR(사우디/리얄)"}, 
  {key: 27, value: "SEK(스웨덴/크로나)"}, 
  {key: 28, value: "SGD(싱가포르/달러)"}, 
  {key: 29, value: "THB(태국/바트)"}, 
  {key: 30, value: "USD(미국/달러)"}, 
]