export const countryList = [
  {key: 1, value: "AED(아랍에미리트/디르함)"},
  {key: 2, value: "AUD(호주/달러)"}, 
  {key: 3, value: "BHD(바레인/디나르)"}, 
  {key: 4, value: "BND(브루나이/달러)"}, 
  {key: 5, value: "CAD(캐나다/달러)"}, 
  {key: 6, value: "CHF(스위스/프랑)"}, 
  {key: 7, value: "CNH(중국/위안)"}, 
  {key: 8, value: "DKK(덴마크/크로네)"}, 
  {key: 9, value: "EUR(유럽 연합/유로)"}, 
  {key: 10, value: "GBP(영국/파운드)"}, 
  {key: 11, value: "HKD(홍콩/달러)"}, 
  {key: 12, value: "IDR(인도네시아/루피아)"},
  {key: 13, value: "JPY(일본/옌)"}, 
  {key: 14, value: "KRW(한국/원)"}, 
  {key: 15, value: "KWD(쿠웨이트/디나르)"},
  {key: 16, value: "MYR(말레이지아/링기트)"}, 
  {key: 17, value: "NOK(노르웨이/크로네)"}, 
  {key: 18, value: "NZD(뉴질랜드/달러)"}, 
  {key: 19, value: "SAR(사우디/리얄)"}, 
  {key: 20, value: "SEK(스웨덴/크로나)"}, 
  {key: 21, value: "SGD(싱가포르/달러)"}, 
  {key: 22, value: "THB(태국/바트)"}, 
  {key: 23, value: "USD(미국/달러)"}, 
]